// data.js

export async function climateData(models) {
  console.log("Adding city: Paris.");
  const paris = await models.Cities.create({
    city: "Paris",
    country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
  });

  console.log("Adding climate data: Paris.");
  await models.Climate.bulkCreate([{
      cityId: paris.id,
      month: 1,
      avgHighTemp: 7,
      avgLowTemp: 3,
      avgRainfallmm: 54,
      avgRainfallDays: 15,
      avgSunshineHours: 62,
      uvIndex: 1,
    },
    {
      cityId: paris.id,
      month: 2,
      avgHighTemp: 9,
      avgLowTemp: 3,
      avgRainfallmm: 46,
      avgRainfallDays: 13,
      avgSunshineHours: 88,
      uvIndex: 2,
    },
    {
      cityId: paris.id,
      month: 3,
      avgHighTemp: 12,
      avgLowTemp: 5,
      avgRainfallmm: 51,
      avgRainfallDays: 13,
      avgSunshineHours: 118,
      uvIndex: 3,
    },
    {
      cityId: paris.id,
      month: 4,
      avgHighTemp: 16,
      avgLowTemp: 8,
      avgRainfallmm: 45,
      avgRainfallDays: 12,
      avgSunshineHours: 178,
      uvIndex: 5,
    },
    {
      cityId: paris.id,
      month: 5,
      avgHighTemp: 20,
      avgLowTemp: 12,
      avgRainfallmm: 60,
      avgRainfallDays: 12,
      avgSunshineHours: 190,
      uvIndex: 6,
    },
    {
      cityId: paris.id,
      month: 6,
      avgHighTemp: 23,
      avgLowTemp: 15,
      avgRainfallmm: 54,
      avgRainfallDays: 10,
      avgSunshineHours: 212,
      uvIndex: 7,
    },
    {
      cityId: paris.id,
      month: 7,
      avgHighTemp: 25,
      avgLowTemp: 17,
      avgRainfallmm: 58,
      avgRainfallDays: 10,
      avgSunshineHours: 212,
      uvIndex: 7,
    },
    {
      cityId: paris.id,
      month: 8,
      avgHighTemp: 25,
      avgLowTemp: 17,
      avgRainfallmm: 51,
      avgRainfallDays: 9,
      avgSunshineHours: 212,
      uvIndex: 6,
    },
    {
      cityId: paris.id,
      month: 9,
      avgHighTemp: 21,
      avgLowTemp: 14,
      avgRainfallmm: 54,
      avgRainfallDays: 10,
      avgSunshineHours: 168,
      uvIndex: 4,
    },
    {
      cityId: paris.id,
      month: 10,
      avgHighTemp: 16,
      avgLowTemp: 10,
      avgRainfallmm: 57,
      avgRainfallDays: 12,
      avgSunshineHours: 124,
      uvIndex: 3,
    },
    {
      cityId: paris.id,
      month: 11,
      avgHighTemp: 10,
      avgLowTemp: 6,
      avgRainfallmm: 52,
      avgRainfallDays: 15,
      avgSunshineHours: 66,
      uvIndex: 1,
    },
    {
      cityId: paris.id,
      month: 12,
      avgHighTemp: 7,
      avgLowTemp: 4,
      avgRainfallmm: 55,
      avgRainfallDays: 15,
      avgSunshineHours: 54,
      uvIndex: 1,
    },
  ]);

  // Create Budapest city
  console.log("Adding city: Budapest.");
  const budapest = await models.Cities.create({
    city: "Budapest",
    country: "Hungary",
    latitude: 47.4979,
    longitude: 19.0402,
  });

  console.log("Adding climate data: Budapest.");
  await models.Climate.bulkCreate([{
      cityId: budapest.id,
      month: 1,
      avgHighTemp: 3,
      avgLowTemp: -2,
      avgRainfallmm: 35,
      avgRainfallDays: 10,
      avgSunshineHours: 45,
      uvIndex: 1,
    },
    {
      cityId: budapest.id,
      month: 2,
      avgHighTemp: 6,
      avgLowTemp: -1,
      avgRainfallmm: 30,
      avgRainfallDays: 9,
      avgSunshineHours: 80,
      uvIndex: 2,
    },
    {
      cityId: budapest.id,
      month: 3,
      avgHighTemp: 12,
      avgLowTemp: 1,
      avgRainfallmm: 40,
      avgRainfallDays: 11,
      avgSunshineHours: 130,
      uvIndex: 4,
    },
    {
      cityId: budapest.id,
      month: 4,
      avgHighTemp: 17,
      avgLowTemp: 6,
      avgRainfallmm: 50,
      avgRainfallDays: 11,
      avgSunshineHours: 180,
      uvIndex: 5,
    },
    {
      cityId: budapest.id,
      month: 5,
      avgHighTemp: 22,
      avgLowTemp: 11,
      avgRainfallmm: 60,
      avgRainfallDays: 12,
      avgSunshineHours: 210,
      uvIndex: 7,
    },
    {
      cityId: budapest.id,
      month: 6,
      avgHighTemp: 26,
      avgLowTemp: 15,
      avgRainfallmm: 70,
      avgRainfallDays: 12,
      avgSunshineHours: 220,
      uvIndex: 8,
    },
    {
      cityId: budapest.id,
      month: 7,
      avgHighTemp: 28,
      avgLowTemp: 17,
      avgRainfallmm: 55,
      avgRainfallDays: 10,
      avgSunshineHours: 230,
      uvIndex: 8,
    },
    {
      cityId: budapest.id,
      month: 8,
      avgHighTemp: 28,
      avgLowTemp: 16,
      avgRainfallmm: 65,
      avgRainfallDays: 11,
      avgSunshineHours: 210,
      uvIndex: 7,
    },
    {
      cityId: budapest.id,
      month: 9,
      avgHighTemp: 24,
      avgLowTemp: 12,
      avgRainfallmm: 50,
      avgRainfallDays: 10,
      avgSunshineHours: 180,
      uvIndex: 5,
    },
    {
      cityId: budapest.id,
      month: 10,
      avgHighTemp: 17,
      avgLowTemp: 7,
      avgRainfallmm: 40,
      avgRainfallDays: 9,
      avgSunshineHours: 130,
      uvIndex: 3,
    },
    {
      cityId: budapest.id,
      month: 11,
      avgHighTemp: 10,
      avgLowTemp: 2,
      avgRainfallmm: 35,
      avgRainfallDays: 9,
      avgSunshineHours: 70,
      uvIndex: 2,
    },
    {
      cityId: budapest.id,
      month: 12,
      avgHighTemp: 5,
      avgLowTemp: -1,
      avgRainfallmm: 30,
      avgRainfallDays: 9,
      avgSunshineHours: 50,
      uvIndex: 1,
    },
  ]);

  // Create Cape Town city
  console.log("Adding city: Cape Town.");
  const capeTown = await models.Cities.create({
    city: "Cape Town",
    country: "South Africa",
    latitude: -33.9249,
    longitude: 18.4241,
  });

  console.log("Adding climate data: Cape Town.");
  await models.Climate.bulkCreate([{
      cityId: capeTown.id,
      month: 1, // Summer in Southern Hemisphere
      avgHighTemp: 26,
      avgLowTemp: 16,
      avgRainfallmm: 14,
      avgRainfallDays: 2,
      avgSunshineHours: 350,
      uvIndex: 11, // Very high UV in summer
    },
    {
      cityId: capeTown.id,
      month: 2,
      avgHighTemp: 27,
      avgLowTemp: 16,
      avgRainfallmm: 18,
      avgRainfallDays: 2,
      avgSunshineHours: 320,
      uvIndex: 10,
    },
    {
      cityId: capeTown.id,
      month: 3,
      avgHighTemp: 25,
      avgLowTemp: 15,
      avgRainfallmm: 20,
      avgRainfallDays: 3,
      avgSunshineHours: 290,
      uvIndex: 8,
    },
    {
      cityId: capeTown.id,
      month: 4,
      avgHighTemp: 23,
      avgLowTemp: 13,
      avgRainfallmm: 40,
      avgRainfallDays: 5,
      avgSunshineHours: 250,
      uvIndex: 6,
    },
    {
      cityId: capeTown.id,
      month: 5,
      avgHighTemp: 20,
      avgLowTemp: 11,
      avgRainfallmm: 70,
      avgRainfallDays: 8,
      avgSunshineHours: 200,
      uvIndex: 4,
    },
    {
      cityId: capeTown.id,
      month: 6, // Winter in Southern Hemisphere
      avgHighTemp: 18,
      avgLowTemp: 9,
      avgRainfallmm: 90,
      avgRainfallDays: 10,
      avgSunshineHours: 180,
      uvIndex: 3,
    },
    {
      cityId: capeTown.id,
      month: 7,
      avgHighTemp: 18,
      avgLowTemp: 8,
      avgRainfallmm: 80,
      avgRainfallDays: 9,
      avgSunshineHours: 190,
      uvIndex: 3,
    },
    {
      cityId: capeTown.id,
      month: 8,
      avgHighTemp: 19,
      avgLowTemp: 9,
      avgRainfallmm: 77,
      avgRainfallDays: 9,
      avgSunshineHours: 210,
      uvIndex: 4,
    },
    {
      cityId: capeTown.id,
      month: 9,
      avgHighTemp: 20,
      avgLowTemp: 10,
      avgRainfallmm: 40,
      avgRainfallDays: 6,
      avgSunshineHours: 250,
      uvIndex: 6,
    },
    {
      cityId: capeTown.id,
      month: 10,
      avgHighTemp: 22,
      avgLowTemp: 12,
      avgRainfallmm: 30,
      avgRainfallDays: 4,
      avgSunshineHours: 280,
      uvIndex: 8,
    },
    {
      cityId: capeTown.id,
      month: 11,
      avgHighTemp: 24,
      avgLowTemp: 14,
      avgRainfallmm: 18,
      avgRainfallDays: 3,
      avgSunshineHours: 310,
      uvIndex: 10,
    },
    {
      cityId: capeTown.id,
      month: 12,
      avgHighTemp: 26,
      avgLowTemp: 16,
      avgRainfallmm: 15,
      avgRainfallDays: 2,
      avgSunshineHours: 340,
      uvIndex: 11,
    },
  ]);

  // Create Berlin city
  console.log("Adding city: Berlin.");
  const berlin = await models.Cities.create({
    city: "Berlin",
    country: "Germany",
    latitude: 52.52,
    longitude: 13.405,
  });

  console.log("Adding climate data: Berlin.");
  await models.Climate.bulkCreate([{
      cityId: berlin.id,
      month: 1,
      avgHighTemp: 3,
      avgLowTemp: -2,
      avgRainfallmm: 42,
      avgRainfallDays: 10,
      avgSunshineHours: 45,
      uvIndex: 1,
    },
    {
      cityId: berlin.id,
      month: 2,
      avgHighTemp: 5,
      avgLowTemp: -2,
      avgRainfallmm: 34,
      avgRainfallDays: 8,
      avgSunshineHours: 75,
      uvIndex: 1,
    },
    {
      cityId: berlin.id,
      month: 3,
      avgHighTemp: 10,
      avgLowTemp: 1,
      avgRainfallmm: 40,
      avgRainfallDays: 9,
      avgSunshineHours: 110,
      uvIndex: 3,
    },
    {
      cityId: berlin.id,
      month: 4,
      avgHighTemp: 15,
      avgLowTemp: 5,
      avgRainfallmm: 41,
      avgRainfallDays: 8,
      avgSunshineHours: 160,
      uvIndex: 4,
    },
    {
      cityId: berlin.id,
      month: 5,
      avgHighTemp: 20,
      avgLowTemp: 10,
      avgRainfallmm: 55,
      avgRainfallDays: 9,
      avgSunshineHours: 220,
      uvIndex: 6,
    },
    {
      cityId: berlin.id,
      month: 6,
      avgHighTemp: 23,
      avgLowTemp: 13,
      avgRainfallmm: 68,
      avgRainfallDays: 10,
      avgSunshineHours: 230,
      uvIndex: 6,
    },
    {
      cityId: berlin.id,
      month: 7,
      avgHighTemp: 25,
      avgLowTemp: 15,
      avgRainfallmm: 58,
      avgRainfallDays: 9,
      avgSunshineHours: 235,
      uvIndex: 6,
    },
    {
      cityId: berlin.id,
      month: 8,
      avgHighTemp: 24,
      avgLowTemp: 14,
      avgRainfallmm: 58,
      avgRainfallDays: 8,
      avgSunshineHours: 225,
      uvIndex: 6,
    },
    {
      cityId: berlin.id,
      month: 9,
      avgHighTemp: 20,
      avgLowTemp: 11,
      avgRainfallmm: 45,
      avgRainfallDays: 8,
      avgSunshineHours: 165,
      uvIndex: 4,
    },
    {
      cityId: berlin.id,
      month: 10,
      avgHighTemp: 14,
      avgLowTemp: 7,
      avgRainfallmm: 36,
      avgRainfallDays: 9,
      avgSunshineHours: 110,
      uvIndex: 2,
    },
    {
      cityId: berlin.id,
      month: 11,
      avgHighTemp: 8,
      avgLowTemp: 3,
      avgRainfallmm: 48,
      avgRainfallDays: 10,
      avgSunshineHours: 55,
      uvIndex: 1,
    },
    {
      cityId: berlin.id,
      month: 12,
      avgHighTemp: 4,
      avgLowTemp: 0,
      avgRainfallmm: 51,
      avgRainfallDays: 11,
      avgSunshineHours: 45,
      uvIndex: 1,
    },
  ]);

  // Create London city
  console.log("Adding city: London.");
  const london = await models.Cities.create({
    city: "London",
    country: "United Kingdom",
    latitude: 51.5072,
    longitude: -0.1276,
  });

  console.log("Adding climate data: London.");
  await models.Climate.bulkCreate([{
      cityId: london.id,
      month: 1,
      avgHighTemp: 8,
      avgLowTemp: 3,
      avgRainfallmm: 55,
      avgRainfallDays: 12,
      avgSunshineHours: 61,
      uvIndex: 1,
    },
    {
      cityId: london.id,
      month: 2,
      avgHighTemp: 8,
      avgLowTemp: 3,
      avgRainfallmm: 40,
      avgRainfallDays: 9,
      avgSunshineHours: 78,
      uvIndex: 2,
    },
    {
      cityId: london.id,
      month: 3,
      avgHighTemp: 11,
      avgLowTemp: 5,
      avgRainfallmm: 42,
      avgRainfallDays: 9,
      avgSunshineHours: 115,
      uvIndex: 3,
    },
    {
      cityId: london.id,
      month: 4,
      avgHighTemp: 14,
      avgLowTemp: 7,
      avgRainfallmm: 43,
      avgRainfallDays: 8,
      avgSunshineHours: 168,
      uvIndex: 4,
    },
    {
      cityId: london.id,
      month: 5,
      avgHighTemp: 18,
      avgLowTemp: 10,
      avgRainfallmm: 47,
      avgRainfallDays: 8,
      avgSunshineHours: 192,
      uvIndex: 5,
    },
    {
      cityId: london.id,
      month: 6,
      avgHighTemp: 21,
      avgLowTemp: 13,
      avgRainfallmm: 45,
      avgRainfallDays: 7,
      avgSunshineHours: 200,
      uvIndex: 6,
    },
    {
      cityId: london.id,
      month: 7,
      avgHighTemp: 24,
      avgLowTemp: 15,
      avgRainfallmm: 40,
      avgRainfallDays: 6,
      avgSunshineHours: 212,
      uvIndex: 6,
    },
    {
      cityId: london.id,
      month: 8,
      avgHighTemp: 23,
      avgLowTemp: 15,
      avgRainfallmm: 48,
      avgRainfallDays: 7,
      avgSunshineHours: 202,
      uvIndex: 5,
    },
    {
      cityId: london.id,
      month: 9,
      avgHighTemp: 20,
      avgLowTemp: 13,
      avgRainfallmm: 49,
      avgRainfallDays: 8,
      avgSunshineHours: 150,
      uvIndex: 4,
    },
    {
      cityId: london.id,
      month: 10,
      avgHighTemp: 15,
      avgLowTemp: 10,
      avgRainfallmm: 71,
      avgRainfallDays: 10,
      avgSunshineHours: 116,
      uvIndex: 2,
    },
    {
      cityId: london.id,
      month: 11,
      avgHighTemp: 11,
      avgLowTemp: 6,
      avgRainfallmm: 63,
      avgRainfallDays: 10,
      avgSunshineHours: 70,
      uvIndex: 1,
    },
    {
      cityId: london.id,
      month: 12,
      avgHighTemp: 8,
      avgLowTemp: 4,
      avgRainfallmm: 55,
      avgRainfallDays: 11,
      avgSunshineHours: 57,
      uvIndex: 1,
    },
  ]);

  // Create Nairobi city
  console.log("Adding city: Nairobi.");
  const nairobi = await models.Cities.create({
    city: "Nairobi",
    country: "Kenya",
    latitude: -1.286389,
    longitude: 36.817223,
  });

  console.log("Adding climate data: Nairobi.");
  await models.Climate.bulkCreate([{
      cityId: nairobi.id,
      month: 1,
      avgHighTemp: 26,
      avgLowTemp: 13,
      avgRainfallmm: 50,
      avgRainfallDays: 5,
      avgSunshineHours: 270,
      uvIndex: 12, // Very high UV near equator
    },
    {
      cityId: nairobi.id,
      month: 2,
      avgHighTemp: 27,
      avgLowTemp: 13,
      avgRainfallmm: 40,
      avgRainfallDays: 4,
      avgSunshineHours: 260,
      uvIndex: 12,
    },
    {
      cityId: nairobi.id,
      month: 3,
      avgHighTemp: 27,
      avgLowTemp: 14,
      avgRainfallmm: 90,
      avgRainfallDays: 9,
      avgSunshineHours: 240,
      uvIndex: 11,
    },
    {
      cityId: nairobi.id,
      month: 4,
      avgHighTemp: 25,
      avgLowTemp: 14,
      avgRainfallmm: 240,
      avgRainfallDays: 17,
      avgSunshineHours: 180,
      uvIndex: 10,
    },
    {
      cityId: nairobi.id,
      month: 5,
      avgHighTemp: 24,
      avgLowTemp: 13,
      avgRainfallmm: 180,
      avgRainfallDays: 15,
      avgSunshineHours: 170,
      uvIndex: 9,
    },
    {
      cityId: nairobi.id,
      month: 6,
      avgHighTemp: 22,
      avgLowTemp: 11,
      avgRainfallmm: 30,
      avgRainfallDays: 4,
      avgSunshineHours: 200,
      uvIndex: 10,
    },
    {
      cityId: nairobi.id,
      month: 7,
      avgHighTemp: 21,
      avgLowTemp: 10,
      avgRainfallmm: 20,
      avgRainfallDays: 3,
      avgSunshineHours: 210,
      uvIndex: 10,
    },
    {
      cityId: nairobi.id,
      month: 8,
      avgHighTemp: 22,
      avgLowTemp: 10,
      avgRainfallmm: 20,
      avgRainfallDays: 3,
      avgSunshineHours: 210,
      uvIndex: 11,
    },
    {
      cityId: nairobi.id,
      month: 9,
      avgHighTemp: 25,
      avgLowTemp: 12,
      avgRainfallmm: 30,
      avgRainfallDays: 4,
      avgSunshineHours: 230,
      uvIndex: 11,
    },
    {
      cityId: nairobi.id,
      month: 10,
      avgHighTemp: 26,
      avgLowTemp: 13,
      avgRainfallmm: 90,
      avgRainfallDays: 9,
      avgSunshineHours: 220,
      uvIndex: 11,
    },
    {
      cityId: nairobi.id,
      month: 11,
      avgHighTemp: 24,
      avgLowTemp: 13,
      avgRainfallmm: 150,
      avgRainfallDays: 13,
      avgSunshineHours: 200,
      uvIndex: 11,
    },
    {
      cityId: nairobi.id,
      month: 12,
      avgHighTemp: 24,
      avgLowTemp: 13,
      avgRainfallmm: 70,
      avgRainfallDays: 6,
      avgSunshineHours: 240,
      uvIndex: 12,
    },
  ]);

  // Create Tokyo city
  console.log("Adding city: Tokyo.");
  const tokyo = await models.Cities.create({
    city: "Tokyo",
    country: "Japan",
    latitude: 35.6895,
    longitude: 139.6917,
  });

  console.log("Adding climate data: Tokyo.");
  await models.Climate.bulkCreate([{
      cityId: tokyo.id,
      month: 1,
      avgHighTemp: 10,
      avgLowTemp: 2,
      avgRainfallmm: 50,
      avgRainfallDays: 5,
      avgSunshineHours: 180,
      uvIndex: 2,
    },
    {
      cityId: tokyo.id,
      month: 2,
      avgHighTemp: 11,
      avgLowTemp: 2,
      avgRainfallmm: 60,
      avgRainfallDays: 6,
      avgSunshineHours: 175,
      uvIndex: 3,
    },
    {
      cityId: tokyo.id,
      month: 3,
      avgHighTemp: 14,
      avgLowTemp: 5,
      avgRainfallmm: 110,
      avgRainfallDays: 10,
      avgSunshineHours: 160,
      uvIndex: 5,
    },
    {
      cityId: tokyo.id,
      month: 4,
      avgHighTemp: 19,
      avgLowTemp: 10,
      avgRainfallmm: 125,
      avgRainfallDays: 10,
      avgSunshineHours: 170,
      uvIndex: 7,
    },
    {
      cityId: tokyo.id,
      month: 5,
      avgHighTemp: 23,
      avgLowTemp: 15,
      avgRainfallmm: 135,
      avgRainfallDays: 10,
      avgSunshineHours: 170,
      uvIndex: 8,
    },
    {
      cityId: tokyo.id,
      month: 6,
      avgHighTemp: 25,
      avgLowTemp: 19,
      avgRainfallmm: 160,
      avgRainfallDays: 12,
      avgSunshineHours: 130,
      uvIndex: 8,
    },
    {
      cityId: tokyo.id,
      month: 7,
      avgHighTemp: 29,
      avgLowTemp: 23,
      avgRainfallmm: 155,
      avgRainfallDays: 10,
      avgSunshineHours: 170,
      uvIndex: 9,
    },
    {
      cityId: tokyo.id,
      month: 8,
      avgHighTemp: 31,
      avgLowTemp: 24,
      avgRainfallmm: 170,
      avgRainfallDays: 10,
      avgSunshineHours: 190,
      uvIndex: 9,
    },
    {
      cityId: tokyo.id,
      month: 9,
      avgHighTemp: 27,
      avgLowTemp: 21,
      avgRainfallmm: 210,
      avgRainfallDays: 12,
      avgSunshineHours: 140,
      uvIndex: 7,
    },
    {
      cityId: tokyo.id,
      month: 10,
      avgHighTemp: 21,
      avgLowTemp: 15,
      avgRainfallmm: 160,
      avgRainfallDays: 9,
      avgSunshineHours: 165,
      uvIndex: 5,
    },
    {
      cityId: tokyo.id,
      month: 11,
      avgHighTemp: 16,
      avgLowTemp: 9,
      avgRainfallmm: 90,
      avgRainfallDays: 6,
      avgSunshineHours: 170,
      uvIndex: 3,
    },
    {
      cityId: tokyo.id,
      month: 12,
      avgHighTemp: 12,
      avgLowTemp: 5,
      avgRainfallmm: 50,
      avgRainfallDays: 4,
      avgSunshineHours: 180,
      uvIndex: 2,
    },
  ]);

  // Create Miami city
  console.log("Adding city: Miami.");
  const miami = await models.Cities.create({
    city: "Miami",
    country: "United States",
    latitude: 25.7617,
    longitude: -80.1918,
  });

  console.log("Adding climate data: Miami.");
  await models.Climate.bulkCreate([{
      cityId: miami.id,
      month: 1, // Dry season
      avgHighTemp: 24,
      avgLowTemp: 15,
      avgRainfallmm: 51,
      avgRainfallDays: 6,
      avgSunshineHours: 220,
      uvIndex: 6,
    },
    {
      cityId: miami.id,
      month: 2,
      avgHighTemp: 25,
      avgLowTemp: 16,
      avgRainfallmm: 53,
      avgRainfallDays: 6,
      avgSunshineHours: 230,
      uvIndex: 7,
    },
    {
      cityId: miami.id,
      month: 3,
      avgHighTemp: 27,
      avgLowTemp: 18,
      avgRainfallmm: 64,
      avgRainfallDays: 6,
      avgSunshineHours: 260,
      uvIndex: 8,
    },
    {
      cityId: miami.id,
      month: 4,
      avgHighTemp: 29,
      avgLowTemp: 21,
      avgRainfallmm: 78,
      avgRainfallDays: 7,
      avgSunshineHours: 280,
      uvIndex: 9,
    },
    {
      cityId: miami.id,
      month: 5, // Transition to wet season
      avgHighTemp: 31,
      avgLowTemp: 24,
      avgRainfallmm: 165,
      avgRainfallDays: 12,
      avgSunshineHours: 290,
      uvIndex: 10,
    },
    {
      cityId: miami.id,
      month: 6, // Wet season begins
      avgHighTemp: 32,
      avgLowTemp: 26,
      avgRainfallmm: 237,
      avgRainfallDays: 16,
      avgSunshineHours: 270,
      uvIndex: 11,
    },
    {
      cityId: miami.id,
      month: 7,
      avgHighTemp: 33,
      avgLowTemp: 27,
      avgRainfallmm: 149,
      avgRainfallDays: 13,
      avgSunshineHours: 290,
      uvIndex: 11,
    },
    {
      cityId: miami.id,
      month: 8,
      avgHighTemp: 33,
      avgLowTemp: 27,
      avgRainfallmm: 200,
      avgRainfallDays: 15,
      avgSunshineHours: 280,
      uvIndex: 10,
    },
    {
      cityId: miami.id,
      month: 9, // Peak wet season
      avgHighTemp: 32,
      avgLowTemp: 26,
      avgRainfallmm: 194,
      avgRainfallDays: 14,
      avgSunshineHours: 250,
      uvIndex: 9,
    },
    {
      cityId: miami.id,
      month: 10, // Wet season continues
      avgHighTemp: 30,
      avgLowTemp: 23,
      avgRainfallmm: 143,
      avgRainfallDays: 11,
      avgSunshineHours: 240,
      uvIndex: 8,
    },
    {
      cityId: miami.id,
      month: 11, // Transition to dry season
      avgHighTemp: 27,
      avgLowTemp: 20,
      avgRainfallmm: 71,
      avgRainfallDays: 7,
      avgSunshineHours: 230,
      uvIndex: 7,
    },
    {
      cityId: miami.id,
      month: 12, // Dry season
      avgHighTemp: 25,
      avgLowTemp: 17,
      avgRainfallmm: 51,
      avgRainfallDays: 6,
      avgSunshineHours: 210,
      uvIndex: 6,
    },
  ]);

  // Create Taipei
  console.log("Adding city: Taipei.");
  const taipei = await models.Cities.create({
    city: "Taipei",
    country: "Taiwan",
    latitude: 25.0330,
    longitude: 121.5654,
  });

  console.log("Adding climate data: Taipei.");
  await models.Climate.bulkCreate([{
      cityId: taipei.id,
      month: 1,
      avgHighTemp: 19,
      avgLowTemp: 12,
      avgRainfallmm: 84,
      avgRainfallDays: 13,
      avgSunshineHours: 90,
      uvIndex: 4,
    },
    {
      cityId: taipei.id,
      month: 2,
      avgHighTemp: 19,
      avgLowTemp: 12,
      avgRainfallmm: 171,
      avgRainfallDays: 16,
      avgSunshineHours: 80,
      uvIndex: 5,
    },
    {
      cityId: taipei.id,
      month: 3,
      avgHighTemp: 22,
      avgLowTemp: 15,
      avgRainfallmm: 180,
      avgRainfallDays: 17,
      avgSunshineHours: 90,
      uvIndex: 6,
    },
    {
      cityId: taipei.id,
      month: 4,
      avgHighTemp: 25,
      avgLowTemp: 18,
      avgRainfallmm: 178,
      avgRainfallDays: 15,
      avgSunshineHours: 100,
      uvIndex: 8,
    },
    {
      cityId: taipei.id,
      month: 5,
      avgHighTemp: 29,
      avgLowTemp: 22,
      avgRainfallmm: 234,
      avgRainfallDays: 16,
      avgSunshineHours: 130,
      uvIndex: 10,
    },
    {
      cityId: taipei.id,
      month: 6, // Wet season
      avgHighTemp: 32,
      avgLowTemp: 25,
      avgRainfallmm: 325,
      avgRainfallDays: 17,
      avgSunshineHours: 140,
      uvIndex: 11,
    },
    {
      cityId: taipei.id,
      month: 7,
      avgHighTemp: 34,
      avgLowTemp: 27,
      avgRainfallmm: 247,
      avgRainfallDays: 13,
      avgSunshineHours: 200,
      uvIndex: 11,
    },
    {
      cityId: taipei.id,
      month: 8,
      avgHighTemp: 33,
      avgLowTemp: 26,
      avgRainfallmm: 322,
      avgRainfallDays: 15,
      avgSunshineHours: 180,
      uvIndex: 10,
    },
    {
      cityId: taipei.id,
      month: 9,
      avgHighTemp: 31,
      avgLowTemp: 24,
      avgRainfallmm: 200,
      avgRainfallDays: 11,
      avgSunshineHours: 160,
      uvIndex: 9,
    },
    {
      cityId: taipei.id,
      month: 10,
      avgHighTemp: 27,
      avgLowTemp: 20,
      avgRainfallmm: 51,
      avgRainfallDays: 6,
      avgSunshineHours: 140,
      uvIndex: 7,
    },
    {
      cityId: taipei.id,
      month: 11,
      avgHighTemp: 24,
      avgLowTemp: 17,
      avgRainfallmm: 83,
      avgRainfallDays: 9,
      avgSunshineHours: 110,
      uvIndex: 5,
    },
    {
      cityId: taipei.id,
      month: 12,
      avgHighTemp: 20,
      avgLowTemp: 13,
      avgRainfallmm: 68,
      avgRainfallDays: 10,
      avgSunshineHours: 100,
      uvIndex: 4,
    },
  ]);

  // Create Seoul
  console.log("Adding city: Seoul.");
  const seoul = await models.Cities.create({
    city: "Seoul",
    country: "South Korea",
    latitude: 37.5665,
    longitude: 126.9780,
  });

  console.log("Adding climate data: Seoul.");
  await models.Climate.bulkCreate([{
      cityId: seoul.id,
      month: 1,
      avgHighTemp: 2,
      avgLowTemp: -6,
      avgRainfallmm: 21,
      avgRainfallDays: 7,
      avgSunshineHours: 160,
      uvIndex: 2,
    },
    {
      cityId: seoul.id,
      month: 2,
      avgHighTemp: 5,
      avgLowTemp: -3,
      avgRainfallmm: 24,
      avgRainfallDays: 6,
      avgSunshineHours: 180,
      uvIndex: 3,
    },
    {
      cityId: seoul.id,
      month: 3,
      avgHighTemp: 10,
      avgLowTemp: 2,
      avgRainfallmm: 46,
      avgRainfallDays: 8,
      avgSunshineHours: 200,
      uvIndex: 5,
    },
    {
      cityId: seoul.id,
      month: 4,
      avgHighTemp: 18,
      avgLowTemp: 8,
      avgRainfallmm: 94,
      avgRainfallDays: 9,
      avgSunshineHours: 220,
      uvIndex: 7,
    },
    {
      cityId: seoul.id,
      month: 5,
      avgHighTemp: 23,
      avgLowTemp: 14,
      avgRainfallmm: 102,
      avgRainfallDays: 9,
      avgSunshineHours: 240,
      uvIndex: 8,
    },
    {
      cityId: seoul.id,
      month: 6, // Rainy season begins
      avgHighTemp: 27,
      avgLowTemp: 19,
      avgRainfallmm: 133,
      avgRainfallDays: 10,
      avgSunshineHours: 180,
      uvIndex: 9,
    },
    {
      cityId: seoul.id,
      month: 7, // Peak monsoon
      avgHighTemp: 29,
      avgLowTemp: 23,
      avgRainfallmm: 395,
      avgRainfallDays: 16,
      avgSunshineHours: 140,
      uvIndex: 9,
    },
    {
      cityId: seoul.id,
      month: 8,
      avgHighTemp: 30,
      avgLowTemp: 24,
      avgRainfallmm: 348,
      avgRainfallDays: 14,
      avgSunshineHours: 180,
      uvIndex: 8,
    },
    {
      cityId: seoul.id,
      month: 9,
      avgHighTemp: 26,
      avgLowTemp: 18,
      avgRainfallmm: 138,
      avgRainfallDays: 8,
      avgSunshineHours: 190,
      uvIndex: 6,
    },
    {
      cityId: seoul.id,
      month: 10,
      avgHighTemp: 20,
      avgLowTemp: 11,
      avgRainfallmm: 49,
      avgRainfallDays: 6,
      avgSunshineHours: 200,
      uvIndex: 4,
    },
    {
      cityId: seoul.id,
      month: 11,
      avgHighTemp: 12,
      avgLowTemp: 3,
      avgRainfallmm: 53,
      avgRainfallDays: 9,
      avgSunshineHours: 160,
      uvIndex: 3,
    },
    {
      cityId: seoul.id,
      month: 12,
      avgHighTemp: 5,
      avgLowTemp: -3,
      avgRainfallmm: 25,
      avgRainfallDays: 7,
      avgSunshineHours: 150,
      uvIndex: 2,
    },
  ]);

  // Create Kuala Lumpur
  console.log("Adding city: Kuala Lumpur.");
  const kualaLumpur = await models.Cities.create({
    city: "Kuala Lumpur",
    country: "Malaysia",
    latitude: 3.1390,
    longitude: 101.6869,
  });

  console.log("Adding climate data: Kuala Lumpur.");
  await models.Climate.bulkCreate([{
      cityId: kualaLumpur.id,
      month: 1,
      avgHighTemp: 32,
      avgLowTemp: 23,
      avgRainfallmm: 239,
      avgRainfallDays: 15,
      avgSunshineHours: 180,
      uvIndex: 11,
    },
    {
      cityId: kualaLumpur.id,
      month: 2, // Dry season
      avgHighTemp: 33,
      avgLowTemp: 23,
      avgRainfallmm: 200,
      avgRainfallDays: 12,
      avgSunshineHours: 190,
      uvIndex: 11,
    },
    {
      cityId: kualaLumpur.id,
      month: 3,
      avgHighTemp: 33,
      avgLowTemp: 24,
      avgRainfallmm: 260,
      avgRainfallDays: 16,
      avgSunshineHours: 180,
      uvIndex: 12,
    },
    {
      cityId: kualaLumpur.id,
      month: 4,
      avgHighTemp: 33,
      avgLowTemp: 24,
      avgRainfallmm: 280,
      avgRainfallDays: 17,
      avgSunshineHours: 170,
      uvIndex: 12,
    },
    {
      cityId: kualaLumpur.id,
      month: 5,
      avgHighTemp: 33,
      avgLowTemp: 25,
      avgRainfallmm: 200,
      avgRainfallDays: 13,
      avgSunshineHours: 190,
      uvIndex: 12,
    },
    {
      cityId: kualaLumpur.id,
      month: 6, // Relatively dry
      avgHighTemp: 33,
      avgLowTemp: 25,
      avgRainfallmm: 127,
      avgRainfallDays: 10,
      avgSunshineHours: 200,
      uvIndex: 12,
    },
    {
      cityId: kualaLumpur.id,
      month: 7,
      avgHighTemp: 32,
      avgLowTemp: 24,
      avgRainfallmm: 150,
      avgRainfallDays: 11,
      avgSunshineHours: 200,
      uvIndex: 11,
    },
    {
      cityId: kualaLumpur.id,
      month: 8,
      avgHighTemp: 32,
      avgLowTemp: 24,
      avgRainfallmm: 157,
      avgRainfallDays: 12,
      avgSunshineHours: 190,
      uvIndex: 11,
    },
    {
      cityId: kualaLumpur.id,
      month: 9,
      avgHighTemp: 32,
      avgLowTemp: 24,
      avgRainfallmm: 200,
      avgRainfallDays: 14,
      avgSunshineHours: 170,
      uvIndex: 11,
    },
    {
      cityId: kualaLumpur.id,
      month: 10, // Wet season returns
      avgHighTemp: 32,
      avgLowTemp: 24,
      avgRainfallmm: 290,
      avgRainfallDays: 18,
      avgSunshineHours: 160,
      uvIndex: 11,
    },
    {
      cityId: kualaLumpur.id,
      month: 11,
      avgHighTemp: 31,
      avgLowTemp: 23,
      avgRainfallmm: 267,
      avgRainfallDays: 17,
      avgSunshineHours: 150,
      uvIndex: 10,
    },
    {
      cityId: kualaLumpur.id,
      month: 12,
      avgHighTemp: 31,
      avgLowTemp: 23,
      avgRainfallmm: 250,
      avgRainfallDays: 16,
      avgSunshineHours: 160,
      uvIndex: 10,
    },
  ]);

  // Create Mexico City (CDMX)
  console.log("Adding city: Mexico City.");
  const mexicoCity = await models.Cities.create({
    city: "Mexico City",
    country: "Mexico",
    latitude: 19.4326,
    longitude: -99.1332,
  });

  console.log("Adding climate data: Mexico City.");
  await models.Climate.bulkCreate([{
      cityId: mexicoCity.id,
      month: 1, // Dry season
      avgHighTemp: 21,
      avgLowTemp: 6,
      avgRainfallmm: 13,
      avgRainfallDays: 2,
      avgSunshineHours: 240,
      uvIndex: 7,
    },
    {
      cityId: mexicoCity.id,
      month: 2,
      avgHighTemp: 23,
      avgLowTemp: 8,
      avgRainfallmm: 8,
      avgRainfallDays: 2,
      avgSunshineHours: 250,
      uvIndex: 8,
    },
    {
      cityId: mexicoCity.id,
      month: 3,
      avgHighTemp: 26,
      avgLowTemp: 11,
      avgRainfallmm: 16,
      avgRainfallDays: 3,
      avgSunshineHours: 260,
      uvIndex: 10,
    },
    {
      cityId: mexicoCity.id,
      month: 4,
      avgHighTemp: 27,
      avgLowTemp: 13,
      avgRainfallmm: 25,
      avgRainfallDays: 4,
      avgSunshineHours: 250,
      uvIndex: 11,
    },
    {
      cityId: mexicoCity.id,
      month: 5,
      avgHighTemp: 26,
      avgLowTemp: 15,
      avgRainfallmm: 62,
      avgRainfallDays: 10,
      avgSunshineHours: 220,
      uvIndex: 11,
    },
    {
      cityId: mexicoCity.id,
      month: 6, // Rainy season begins
      avgHighTemp: 25,
      avgLowTemp: 15,
      avgRainfallmm: 137,
      avgRainfallDays: 17,
      avgSunshineHours: 180,
      uvIndex: 10,
    },
    {
      cityId: mexicoCity.id,
      month: 7, // Peak rainy season
      avgHighTemp: 23,
      avgLowTemp: 14,
      avgRainfallmm: 170,
      avgRainfallDays: 22,
      avgSunshineHours: 190,
      uvIndex: 10,
    },
    {
      cityId: mexicoCity.id,
      month: 8,
      avgHighTemp: 23,
      avgLowTemp: 14,
      avgRainfallmm: 152,
      avgRainfallDays: 20,
      avgSunshineHours: 190,
      uvIndex: 10,
    },
    {
      cityId: mexicoCity.id,
      month: 9,
      avgHighTemp: 23,
      avgLowTemp: 13,
      avgRainfallmm: 130,
      avgRainfallDays: 17,
      avgSunshineHours: 180,
      uvIndex: 9,
    },
    {
      cityId: mexicoCity.id,
      month: 10,
      avgHighTemp: 22,
      avgLowTemp: 10,
      avgRainfallmm: 51,
      avgRainfallDays: 8,
      avgSunshineHours: 220,
      uvIndex: 8,
    },
    {
      cityId: mexicoCity.id,
      month: 11,
      avgHighTemp: 21,
      avgLowTemp: 8,
      avgRainfallmm: 7,
      avgRainfallDays: 2,
      avgSunshineHours: 240,
      uvIndex: 7,
    },
    {
      cityId: mexicoCity.id,
      month: 12,
      avgHighTemp: 21,
      avgLowTemp: 7,
      avgRainfallmm: 8,
      avgRainfallDays: 1,
      avgSunshineHours: 240,
      uvIndex: 7,
    },
  ]);

  // Create Seattle
  console.log("Adding city: Seattle.");
  const seattle = await models.Cities.create({
    city: "Seattle",
    country: "United States",
    latitude: 47.6062,
    longitude: -122.3321,
  });

  console.log("Adding climate data: Seattle.");
  await models.Climate.bulkCreate([{
      cityId: seattle.id,
      month: 1,
      avgHighTemp: 8,
      avgLowTemp: 2,
      avgRainfallmm: 140,
      avgRainfallDays: 18,
      avgSunshineHours: 70,
      uvIndex: 1,
    },
    {
      cityId: seattle.id,
      month: 2,
      avgHighTemp: 10,
      avgLowTemp: 3,
      avgRainfallmm: 99,
      avgRainfallDays: 15,
      avgSunshineHours: 100,
      uvIndex: 2,
    },
    {
      cityId: seattle.id,
      month: 3,
      avgHighTemp: 13,
      avgLowTemp: 5,
      avgRainfallmm: 94,
      avgRainfallDays: 16,
      avgSunshineHours: 150,
      uvIndex: 4,
    },
    {
      cityId: seattle.id,
      month: 4,
      avgHighTemp: 16,
      avgLowTemp: 7,
      avgRainfallmm: 69,
      avgRainfallDays: 14,
      avgSunshineHours: 190,
      uvIndex: 5,
    },
    {
      cityId: seattle.id,
      month: 5,
      avgHighTemp: 20,
      avgLowTemp: 10,
      avgRainfallmm: 47,
      avgRainfallDays: 10,
      avgSunshineHours: 230,
      uvIndex: 6,
    },
    {
      cityId: seattle.id,
      month: 6,
      avgHighTemp: 23,
      avgLowTemp: 13,
      avgRainfallmm: 37,
      avgRainfallDays: 8,
      avgSunshineHours: 250,
      uvIndex: 7,
    },
    {
      cityId: seattle.id,
      month: 7,
      avgHighTemp: 26,
      avgLowTemp: 15,
      avgRainfallmm: 18,
      avgRainfallDays: 4,
      avgSunshineHours: 290,
      uvIndex: 7,
    },
    {
      cityId: seattle.id,
      month: 8,
      avgHighTemp: 26,
      avgLowTemp: 15,
      avgRainfallmm: 27,
      avgRainfallDays: 5,
      avgSunshineHours: 260,
      uvIndex: 6,
    },
    {
      cityId: seattle.id,
      month: 9,
      avgHighTemp: 22,
      avgLowTemp: 12,
      avgRainfallmm: 47,
      avgRainfallDays: 8,
      avgSunshineHours: 200,
      uvIndex: 5,
    },
    {
      cityId: seattle.id,
      month: 10,
      avgHighTemp: 16,
      avgLowTemp: 8,
      avgRainfallmm: 84,
      avgRainfallDays: 13,
      avgSunshineHours: 130,
      uvIndex: 3,
    },
    {
      cityId: seattle.id,
      month: 11,
      avgHighTemp: 11,
      avgLowTemp: 4,
      avgRainfallmm: 150,
      avgRainfallDays: 18,
      avgSunshineHours: 80,
      uvIndex: 2,
    },
    {
      cityId: seattle.id,
      month: 12,
      avgHighTemp: 8,
      avgLowTemp: 2,
      avgRainfallmm: 140,
      avgRainfallDays: 19,
      avgSunshineHours: 60,
      uvIndex: 1,
    },
  ]);

  // Create Bangkok
  console.log("Adding city: Bangkok.");
  const bangkok = await models.Cities.create({
    city: "Bangkok",
    country: "Thailand",
    latitude: 13.7563,
    longitude: 100.5018,
  });

  console.log("Adding climate data: Bangkok.");
  await models.Climate.bulkCreate([{
      cityId: bangkok.id,
      month: 1, // Cool dry season
      avgHighTemp: 32,
      avgLowTemp: 21,
      avgRainfallmm: 11,
      avgRainfallDays: 2,
      avgSunshineHours: 270,
      uvIndex: 8,
    },
    {
      cityId: bangkok.id,
      month: 2,
      avgHighTemp: 33,
      avgLowTemp: 23,
      avgRainfallmm: 30,
      avgRainfallDays: 3,
      avgSunshineHours: 250,
      uvIndex: 9,
    },
    {
      cityId: bangkok.id,
      month: 3, // Hot season begins
      avgHighTemp: 34,
      avgLowTemp: 25,
      avgRainfallmm: 29,
      avgRainfallDays: 3,
      avgSunshineHours: 250,
      uvIndex: 10,
    },
    {
      cityId: bangkok.id,
      month: 4,
      avgHighTemp: 35,
      avgLowTemp: 26,
      avgRainfallmm: 65,
      avgRainfallDays: 6,
      avgSunshineHours: 240,
      uvIndex: 11,
    },
    {
      cityId: bangkok.id,
      month: 5, // Rainy season starts
      avgHighTemp: 34,
      avgLowTemp: 26,
      avgRainfallmm: 220,
      avgRainfallDays: 18,
      avgSunshineHours: 200,
      uvIndex: 11,
    },
    {
      cityId: bangkok.id,
      month: 6,
      avgHighTemp: 33,
      avgLowTemp: 26,
      avgRainfallmm: 149,
      avgRainfallDays: 15,
      avgSunshineHours: 180,
      uvIndex: 10,
    },
    {
      cityId: bangkok.id,
      month: 7,
      avgHighTemp: 33,
      avgLowTemp: 26,
      avgRainfallmm: 155,
      avgRainfallDays: 16,
      avgSunshineHours: 170,
      uvIndex: 10,
    },
    {
      cityId: bangkok.id,
      month: 8,
      avgHighTemp: 33,
      avgLowTemp: 26,
      avgRainfallmm: 197,
      avgRainfallDays: 17,
      avgSunshineHours: 170,
      uvIndex: 10,
    },
    {
      cityId: bangkok.id,
      month: 9, // Peak rainy season
      avgHighTemp: 32,
      avgLowTemp: 25,
      avgRainfallmm: 344,
      avgRainfallDays: 20,
      avgSunshineHours: 150,
      uvIndex: 9,
    },
    {
      cityId: bangkok.id,
      month: 10,
      avgHighTemp: 32,
      avgLowTemp: 24,
      avgRainfallmm: 242,
      avgRainfallDays: 13,
      avgSunshineHours: 190,
      uvIndex: 8,
    },
    {
      cityId: bangkok.id,
      month: 11, // Cool season returns
      avgHighTemp: 31,
      avgLowTemp: 22,
      avgRainfallmm: 48,
      avgRainfallDays: 4,
      avgSunshineHours: 240,
      uvIndex: 7,
    },
    {
      cityId: bangkok.id,
      month: 12,
      avgHighTemp: 31,
      avgLowTemp: 20,
      avgRainfallmm: 10,
      avgRainfallDays: 1,
      avgSunshineHours: 270,
      uvIndex: 7,
    },
  ]);

  // Create Singapore
  console.log("Adding city: Singapore.");
  const singapore = await models.Cities.create({
    city: "Singapore",
    country: "Singapore",
    latitude: 1.3521,
    longitude: 103.8198,
  });

  console.log("Adding climate data: Singapore.");
  await models.Climate.bulkCreate([{
      cityId: singapore.id,
      month: 1,
      avgHighTemp: 30,
      avgLowTemp: 24,
      avgRainfallmm: 243,
      avgRainfallDays: 15,
      avgSunshineHours: 170,
      uvIndex: 11,
    },
    {
      cityId: singapore.id,
      month: 2,
      avgHighTemp: 31,
      avgLowTemp: 24,
      avgRainfallmm: 156,
      avgRainfallDays: 11,
      avgSunshineHours: 180,
      uvIndex: 11,
    },
    {
      cityId: singapore.id,
      month: 3,
      avgHighTemp: 31,
      avgLowTemp: 25,
      avgRainfallmm: 185,
      avgRainfallDays: 14,
      avgSunshineHours: 180,
      uvIndex: 12,
    },
    {
      cityId: singapore.id,
      month: 4,
      avgHighTemp: 32,
      avgLowTemp: 25,
      avgRainfallmm: 179,
      avgRainfallDays: 15,
      avgSunshineHours: 180,
      uvIndex: 12,
    },
    {
      cityId: singapore.id,
      month: 5,
      avgHighTemp: 32,
      avgLowTemp: 26,
      avgRainfallmm: 171,
      avgRainfallDays: 14,
      avgSunshineHours: 190,
      uvIndex: 12,
    },
    {
      cityId: singapore.id,
      month: 6,
      avgHighTemp: 31,
      avgLowTemp: 26,
      avgRainfallmm: 162,
      avgRainfallDays: 13,
      avgSunshineHours: 180,
      uvIndex: 11,
    },
    {
      cityId: singapore.id,
      month: 7,
      avgHighTemp: 31,
      avgLowTemp: 25,
      avgRainfallmm: 159,
      avgRainfallDays: 13,
      avgSunshineHours: 190,
      uvIndex: 11,
    },
    {
      cityId: singapore.id,
      month: 8,
      avgHighTemp: 31,
      avgLowTemp: 25,
      avgRainfallmm: 176,
      avgRainfallDays: 14,
      avgSunshineHours: 180,
      uvIndex: 11,
    },
    {
      cityId: singapore.id,
      month: 9,
      avgHighTemp: 31,
      avgLowTemp: 25,
      avgRainfallmm: 169,
      avgRainfallDays: 14,
      avgSunshineHours: 170,
      uvIndex: 11,
    },
    {
      cityId: singapore.id,
      month: 10,
      avgHighTemp: 31,
      avgLowTemp: 25,
      avgRainfallmm: 194,
      avgRainfallDays: 16,
      avgSunshineHours: 170,
      uvIndex: 11,
    },
    {
      cityId: singapore.id,
      month: 11,
      avgHighTemp: 30,
      avgLowTemp: 24,
      avgRainfallmm: 254,
      avgRainfallDays: 19,
      avgSunshineHours: 150,
      uvIndex: 10,
    },
    {
      cityId: singapore.id,
      month: 12,
      avgHighTemp: 30,
      avgLowTemp: 24,
      avgRainfallmm: 287,
      avgRainfallDays: 19,
      avgSunshineHours: 150,
      uvIndex: 10,
    },
  ]);

  // Create Beijing
  console.log("Adding city: Beijing.");
  const beijing = await models.Cities.create({
    city: "Beijing",
    country: "China",
    latitude: 39.9042,
    longitude: 116.4074,
  });

  console.log("Adding climate data: Beijing.");
  await models.Climate.bulkCreate([{
      cityId: beijing.id,
      month: 1,
      avgHighTemp: 2,
      avgLowTemp: -8,
      avgRainfallmm: 4,
      avgRainfallDays: 2,
      avgSunshineHours: 180,
      uvIndex: 2,
    },
    {
      cityId: beijing.id,
      month: 2,
      avgHighTemp: 5,
      avgLowTemp: -5,
      avgRainfallmm: 6,
      avgRainfallDays: 3,
      avgSunshineHours: 190,
      uvIndex: 3,
    },
    {
      cityId: beijing.id,
      month: 3,
      avgHighTemp: 12,
      avgLowTemp: 1,
      avgRainfallmm: 9,
      avgRainfallDays: 4,
      avgSunshineHours: 220,
      uvIndex: 5,
    },
    {
      cityId: beijing.id,
      month: 4,
      avgHighTemp: 20,
      avgLowTemp: 8,
      avgRainfallmm: 26,
      avgRainfallDays: 6,
      avgSunshineHours: 250,
      uvIndex: 7,
    },
    {
      cityId: beijing.id,
      month: 5,
      avgHighTemp: 26,
      avgLowTemp: 14,
      avgRainfallmm: 35,
      avgRainfallDays: 7,
      avgSunshineHours: 280,
      uvIndex: 8,
    },
    {
      cityId: beijing.id,
      month: 6,
      avgHighTemp: 30,
      avgLowTemp: 19,
      avgRainfallmm: 78,
      avgRainfallDays: 10,
      avgSunshineHours: 260,
      uvIndex: 9,
    },
    {
      cityId: beijing.id,
      month: 7, // Rainy season
      avgHighTemp: 31,
      avgLowTemp: 22,
      avgRainfallmm: 176,
      avgRainfallDays: 15,
      avgSunshineHours: 220,
      uvIndex: 9,
    },
    {
      cityId: beijing.id,
      month: 8,
      avgHighTemp: 30,
      avgLowTemp: 21,
      avgRainfallmm: 182,
      avgRainfallDays: 14,
      avgSunshineHours: 230,
      uvIndex: 8,
    },
    {
      cityId: beijing.id,
      month: 9,
      avgHighTemp: 26,
      avgLowTemp: 16,
      avgRainfallmm: 49,
      avgRainfallDays: 7,
      avgSunshineHours: 210,
      uvIndex: 6,
    },
    {
      cityId: beijing.id,
      month: 10,
      avgHighTemp: 19,
      avgLowTemp: 8,
      avgRainfallmm: 19,
      avgRainfallDays: 4,
      avgSunshineHours: 200,
      uvIndex: 4,
    },
    {
      cityId: beijing.id,
      month: 11,
      avgHighTemp: 10,
      avgLowTemp: 0,
      avgRainfallmm: 8,
      avgRainfallDays: 3,
      avgSunshineHours: 170,
      uvIndex: 3,
    },
    {
      cityId: beijing.id,
      month: 12,
      avgHighTemp: 4,
      avgLowTemp: -6,
      avgRainfallmm: 3,
      avgRainfallDays: 2,
      avgSunshineHours: 170,
      uvIndex: 2,
    },
  ]);

  // Create Shanghai
  console.log("Adding city: Shanghai.");
  const shanghai = await models.Cities.create({
    city: "Shanghai",
    country: "China",
    latitude: 31.2304,
    longitude: 121.4737,
  });

  console.log("Adding climate data: Shanghai.");
  await models.Climate.bulkCreate([{
      cityId: shanghai.id,
      month: 1,
      avgHighTemp: 8,
      avgLowTemp: 1,
      avgRainfallmm: 74,
      avgRainfallDays: 9,
      avgSunshineHours: 130,
      uvIndex: 3,
    },
    {
      cityId: shanghai.id,
      month: 2,
      avgHighTemp: 10,
      avgLowTemp: 2,
      avgRainfallmm: 59,
      avgRainfallDays: 9,
      avgSunshineHours: 120,
      uvIndex: 4,
    },
    {
      cityId: shanghai.id,
      month: 3,
      avgHighTemp: 14,
      avgLowTemp: 6,
      avgRainfallmm: 93,
      avgRainfallDays: 13,
      avgSunshineHours: 130,
      uvIndex: 5,
    },
    {
      cityId: shanghai.id,
      month: 4,
      avgHighTemp: 20,
      avgLowTemp: 12,
      avgRainfallmm: 74,
      avgRainfallDays: 10,
      avgSunshineHours: 160,
      uvIndex: 7,
    },
    {
      cityId: shanghai.id,
      month: 5,
      avgHighTemp: 25,
      avgLowTemp: 17,
      avgRainfallmm: 84,
      avgRainfallDays: 10,
      avgSunshineHours: 180,
      uvIndex: 8,
    },
    {
      cityId: shanghai.id,
      month: 6, // Rainy season
      avgHighTemp: 28,
      avgLowTemp: 22,
      avgRainfallmm: 181,
      avgRainfallDays: 12,
      avgSunshineHours: 140,
      uvIndex: 9,
    },
    {
      cityId: shanghai.id,
      month: 7,
      avgHighTemp: 32,
      avgLowTemp: 26,
      avgRainfallmm: 146,
      avgRainfallDays: 11,
      avgSunshineHours: 200,
      uvIndex: 10,
    },
    {
      cityId: shanghai.id,
      month: 8,
      avgHighTemp: 32,
      avgLowTemp: 26,
      avgRainfallmm: 142,
      avgRainfallDays: 10,
      avgSunshineHours: 200,
      uvIndex: 9,
    },
    {
      cityId: shanghai.id,
      month: 9,
      avgHighTemp: 28,
      avgLowTemp: 21,
      avgRainfallmm: 130,
      avgRainfallDays: 9,
      avgSunshineHours: 170,
      uvIndex: 7,
    },
    {
      cityId: shanghai.id,
      month: 10,
      avgHighTemp: 22,
      avgLowTemp: 15,
      avgRainfallmm: 56,
      avgRainfallDays: 7,
      avgSunshineHours: 160,
      uvIndex: 5,
    },
    {
      cityId: shanghai.id,
      month: 11,
      avgHighTemp: 16,
      avgLowTemp: 8,
      avgRainfallmm: 52,
      avgRainfallDays: 7,
      avgSunshineHours: 140,
      uvIndex: 4,
    },
    {
      cityId: shanghai.id,
      month: 12,
      avgHighTemp: 10,
      avgLowTemp: 3,
      avgRainfallmm: 43,
      avgRainfallDays: 7,
      avgSunshineHours: 130,
      uvIndex: 3,
    },
  ]);

  // Create New York City
  console.log("Adding city: New York City.");
  const nyc = await models.Cities.create({
    city: "New York City",
    country: "United States",
    latitude: 40.7128,
    longitude: -74.0060,
  });

  console.log("Adding climate data: New York City.");
  await models.Climate.bulkCreate([{
      cityId: nyc.id,
      month: 1,
      avgHighTemp: 4,
      avgLowTemp: -3,
      avgRainfallmm: 89,
      avgRainfallDays: 10,
      avgSunshineHours: 160,
      uvIndex: 2,
    },
    {
      cityId: nyc.id,
      month: 2,
      avgHighTemp: 6,
      avgLowTemp: -2,
      avgRainfallmm: 76,
      avgRainfallDays: 9,
      avgSunshineHours: 180,
      uvIndex: 3,
    },
    {
      cityId: nyc.id,
      month: 3,
      avgHighTemp: 11,
      avgLowTemp: 2,
      avgRainfallmm: 109,
      avgRainfallDays: 11,
      avgSunshineHours: 210,
      uvIndex: 5,
    },
    {
      cityId: nyc.id,
      month: 4,
      avgHighTemp: 17,
      avgLowTemp: 7,
      avgRainfallmm: 105,
      avgRainfallDays: 11,
      avgSunshineHours: 240,
      uvIndex: 6,
    },
    {
      cityId: nyc.id,
      month: 5,
      avgHighTemp: 22,
      avgLowTemp: 13,
      avgRainfallmm: 106,
      avgRainfallDays: 11,
      avgSunshineHours: 270,
      uvIndex: 8,
    },
    {
      cityId: nyc.id,
      month: 6,
      avgHighTemp: 27,
      avgLowTemp: 18,
      avgRainfallmm: 112,
      avgRainfallDays: 10,
      avgSunshineHours: 290,
      uvIndex: 9,
    },
    {
      cityId: nyc.id,
      month: 7,
      avgHighTemp: 29,
      avgLowTemp: 21,
      avgRainfallmm: 117,
      avgRainfallDays: 10,
      avgSunshineHours: 300,
      uvIndex: 9,
    },
    {
      cityId: nyc.id,
      month: 8,
      avgHighTemp: 29,
      avgLowTemp: 21,
      avgRainfallmm: 112,
      avgRainfallDays: 9,
      avgSunshineHours: 280,
      uvIndex: 8,
    },
    {
      cityId: nyc.id,
      month: 9,
      avgHighTemp: 25,
      avgLowTemp: 17,
      avgRainfallmm: 104,
      avgRainfallDays: 8,
      avgSunshineHours: 240,
      uvIndex: 6,
    },
    {
      cityId: nyc.id,
      month: 10,
      avgHighTemp: 19,
      avgLowTemp: 11,
      avgRainfallmm: 91,
      avgRainfallDays: 8,
      avgSunshineHours: 200,
      uvIndex: 4,
    },
    {
      cityId: nyc.id,
      month: 11,
      avgHighTemp: 12,
      avgLowTemp: 5,
      avgRainfallmm: 86,
      avgRainfallDays: 9,
      avgSunshineHours: 160,
      uvIndex: 3,
    },
    {
      cityId: nyc.id,
      month: 12,
      avgHighTemp: 7,
      avgLowTemp: 0,
      avgRainfallmm: 94,
      avgRainfallDays: 10,
      avgSunshineHours: 150,
      uvIndex: 2,
    },
  ]);

  // Create Los Angeles
  console.log("Adding city: Los Angeles.");
  const la = await models.Cities.create({
    city: "Los Angeles",
    country: "United States",
    latitude: 34.0522,
    longitude: -118.2437,
  });

  console.log("Adding climate data: Los Angeles.");
  await models.Climate.bulkCreate([{
      cityId: la.id,
      month: 1,
      avgHighTemp: 20,
      avgLowTemp: 9,
      avgRainfallmm: 79,
      avgRainfallDays: 6,
      avgSunshineHours: 240,
      uvIndex: 4,
    },
    {
      cityId: la.id,
      month: 2,
      avgHighTemp: 20,
      avgLowTemp: 10,
      avgRainfallmm: 97,
      avgRainfallDays: 7,
      avgSunshineHours: 250,
      uvIndex: 5,
    },
    {
      cityId: la.id,
      month: 3,
      avgHighTemp: 21,
      avgLowTemp: 11,
      avgRainfallmm: 73,
      avgRainfallDays: 7,
      avgSunshineHours: 280,
      uvIndex: 7,
    },
    {
      cityId: la.id,
      month: 4,
      avgHighTemp: 23,
      avgLowTemp: 13,
      avgRainfallmm: 25,
      avgRainfallDays: 4,
      avgSunshineHours: 310,
      uvIndex: 8,
    },
    {
      cityId: la.id,
      month: 5,
      avgHighTemp: 24,
      avgLowTemp: 15,
      avgRainfallmm: 10,
      avgRainfallDays: 2,
      avgSunshineHours: 320,
      uvIndex: 9,
    },
    {
      cityId: la.id,
      month: 6,
      avgHighTemp: 26,
      avgLowTemp: 18,
      avgRainfallmm: 5,
      avgRainfallDays: 1,
      avgSunshineHours: 330,
      uvIndex: 10,
    },
    {
      cityId: la.id,
      month: 7,
      avgHighTemp: 28,
      avgLowTemp: 20,
      avgRainfallmm: 2,
      avgRainfallDays: 0,
      avgSunshineHours: 360,
      uvIndex: 10,
    },
    {
      cityId: la.id,
      month: 8,
      avgHighTemp: 29,
      avgLowTemp: 20,
      avgRainfallmm: 3,
      avgRainfallDays: 1,
      avgSunshineHours: 340,
      uvIndex: 9,
    },
    {
      cityId: la.id,
      month: 9,
      avgHighTemp: 28,
      avgLowTemp: 19,
      avgRainfallmm: 9,
      avgRainfallDays: 2,
      avgSunshineHours: 300,
      uvIndex: 8,
    },
    {
      cityId: la.id,
      month: 10,
      avgHighTemp: 25,
      avgLowTemp: 16,
      avgRainfallmm: 15,
      avgRainfallDays: 3,
      avgSunshineHours: 270,
      uvIndex: 6,
    },
    {
      cityId: la.id,
      month: 11,
      avgHighTemp: 22,
      avgLowTemp: 12,
      avgRainfallmm: 32,
      avgRainfallDays: 4,
      avgSunshineHours: 250,
      uvIndex: 5,
    },
    {
      cityId: la.id,
      month: 12,
      avgHighTemp: 20,
      avgLowTemp: 9,
      avgRainfallmm: 66,
      avgRainfallDays: 5,
      avgSunshineHours: 230,
      uvIndex: 4,
    },
  ]);

  // Create Boston
  console.log("Adding city: Boston.");
  const boston = await models.Cities.create({
    city: "Boston",
    country: "United States",
    latitude: 42.3601,
    longitude: -71.0589,
  });

  console.log("Adding climate data: Boston.");
  await models.Climate.bulkCreate([{
      cityId: boston.id,
      month: 1,
      avgHighTemp: 2,
      avgLowTemp: -6,
      avgRainfallmm: 92,
      avgRainfallDays: 11,
      avgSunshineHours: 150,
      uvIndex: 2,
    },
    {
      cityId: boston.id,
      month: 2,
      avgHighTemp: 4,
      avgLowTemp: -4,
      avgRainfallmm: 86,
      avgRainfallDays: 10,
      avgSunshineHours: 170,
      uvIndex: 3,
    },
    {
      cityId: boston.id,
      month: 3,
      avgHighTemp: 8,
      avgLowTemp: 0,
      avgRainfallmm: 111,
      avgRainfallDays: 12,
      avgSunshineHours: 200,
      uvIndex: 4,
    },
    {
      cityId: boston.id,
      month: 4,
      avgHighTemp: 14,
      avgLowTemp: 5,
      avgRainfallmm: 99,
      avgRainfallDays: 11,
      avgSunshineHours: 230,
      uvIndex: 6,
    },
    {
      cityId: boston.id,
      month: 5,
      avgHighTemp: 20,
      avgLowTemp: 11,
      avgRainfallmm: 86,
      avgRainfallDays: 11,
      avgSunshineHours: 260,
      uvIndex: 7,
    },
    {
      cityId: boston.id,
      month: 6,
      avgHighTemp: 25,
      avgLowTemp: 16,
      avgRainfallmm: 85,
      avgRainfallDays: 10,
      avgSunshineHours: 280,
      uvIndex: 8,
    },
    {
      cityId: boston.id,
      month: 7,
      avgHighTemp: 28,
      avgLowTemp: 19,
      avgRainfallmm: 81,
      avgRainfallDays: 9,
      avgSunshineHours: 290,
      uvIndex: 8,
    },
    {
      cityId: boston.id,
      month: 8,
      avgHighTemp: 27,
      avgLowTemp: 19,
      avgRainfallmm: 84,
      avgRainfallDays: 9,
      avgSunshineHours: 270,
      uvIndex: 7,
    },
    {
      cityId: boston.id,
      month: 9,
      avgHighTemp: 23,
      avgLowTemp: 15,
      avgRainfallmm: 87,
      avgRainfallDays: 8,
      avgSunshineHours: 230,
      uvIndex: 6,
    },
    {
      cityId: boston.id,
      month: 10,
      avgHighTemp: 17,
      avgLowTemp: 9,
      avgRainfallmm: 86,
      avgRainfallDays: 9,
      avgSunshineHours: 190,
      uvIndex: 4,
    },
    {
      cityId: boston.id,
      month: 11,
      avgHighTemp: 11,
      avgLowTemp: 3,
      avgRainfallmm: 83,
      avgRainfallDays: 10,
      avgSunshineHours: 150,
      uvIndex: 2,
    },
    {
      cityId: boston.id,
      month: 12,
      avgHighTemp: 5,
      avgLowTemp: -2,
      avgRainfallmm: 99,
      avgRainfallDays: 11,
      avgSunshineHours: 140,
      uvIndex: 2,
    },
  ]);

  // Create Austin
  console.log("Adding city: Austin.");
  const austin = await models.Cities.create({
    city: "Austin",
    country: "United States",
    latitude: 30.2672,
    longitude: -97.7431,
  });

  console.log("Adding climate data: Austin.");
  await models.Climate.bulkCreate([{
      cityId: austin.id,
      month: 1,
      avgHighTemp: 16,
      avgLowTemp: 4,
      avgRainfallmm: 48,
      avgRainfallDays: 7,
      avgSunshineHours: 180,
      uvIndex: 4,
    },
    {
      cityId: austin.id,
      month: 2,
      avgHighTemp: 19,
      avgLowTemp: 7,
      avgRainfallmm: 54,
      avgRainfallDays: 7,
      avgSunshineHours: 200,
      uvIndex: 5,
    },
    {
      cityId: austin.id,
      month: 3,
      avgHighTemp: 24,
      avgLowTemp: 11,
      avgRainfallmm: 73,
      avgRainfallDays: 8,
      avgSunshineHours: 240,
      uvIndex: 7,
    },
    {
      cityId: austin.id,
      month: 4,
      avgHighTemp: 28,
      avgLowTemp: 16,
      avgRainfallmm: 81,
      avgRainfallDays: 7,
      avgSunshineHours: 270,
      uvIndex: 8,
    },
    {
      cityId: austin.id,
      month: 5,
      avgHighTemp: 32,
      avgLowTemp: 21,
      avgRainfallmm: 130,
      avgRainfallDays: 9,
      avgSunshineHours: 300,
      uvIndex: 10,
    },
    {
      cityId: austin.id,
      month: 6,
      avgHighTemp: 35,
      avgLowTemp: 24,
      avgRainfallmm: 91,
      avgRainfallDays: 7,
      avgSunshineHours: 330,
      uvIndex: 11,
    },
    {
      cityId: austin.id,
      month: 7,
      avgHighTemp: 37,
      avgLowTemp: 26,
      avgRainfallmm: 48,
      avgRainfallDays: 5,
      avgSunshineHours: 350,
      uvIndex: 11,
    },
    {
      cityId: austin.id,
      month: 8,
      avgHighTemp: 37,
      avgLowTemp: 26,
      avgRainfallmm: 61,
      avgRainfallDays: 6,
      avgSunshineHours: 340,
      uvIndex: 10,
    },
    {
      cityId: austin.id,
      month: 9,
      avgHighTemp: 34,
      avgLowTemp: 22,
      avgRainfallmm: 86,
      avgRainfallDays: 7,
      avgSunshineHours: 290,
      uvIndex: 8,
    },
    {
      cityId: austin.id,
      month: 10,
      avgHighTemp: 28,
      avgLowTemp: 16,
      avgRainfallmm: 68,
      avgRainfallDays: 6,
      avgSunshineHours: 250,
      uvIndex: 6,
    },
    {
      cityId: austin.id,
      month: 11,
      avgHighTemp: 21,
      avgLowTemp: 9,
      avgRainfallmm: 48,
      avgRainfallDays: 6,
      avgSunshineHours: 200,
      uvIndex: 4,
    },
    {
      cityId: austin.id,
      month: 12,
      avgHighTemp: 17,
      avgLowTemp: 5,
      avgRainfallmm: 51,
      avgRainfallDays: 7,
      avgSunshineHours: 180,
      uvIndex: 3,
    },
  ]);

  // Create Chicago
  console.log("Adding city: Chicago.");
  const chicago = await models.Cities.create({
    city: "Chicago",
    country: "United States",
    latitude: 41.8781,
    longitude: -87.6298,
  });

  console.log("Adding climate data: Chicago.");
  await models.Climate.bulkCreate([{
      cityId: chicago.id,
      month: 1,
      avgHighTemp: -1,
      avgLowTemp: -9,
      avgRainfallmm: 51,
      avgRainfallDays: 11,
      avgSunshineHours: 130,
      uvIndex: 2,
    },
    {
      cityId: chicago.id,
      month: 2,
      avgHighTemp: 2,
      avgLowTemp: -7,
      avgRainfallmm: 48,
      avgRainfallDays: 9,
      avgSunshineHours: 150,
      uvIndex: 3,
    },
    {
      cityId: chicago.id,
      month: 3,
      avgHighTemp: 9,
      avgLowTemp: -1,
      avgRainfallmm: 66,
      avgRainfallDays: 11,
      avgSunshineHours: 190,
      uvIndex: 4,
    },
    {
      cityId: chicago.id,
      month: 4,
      avgHighTemp: 16,
      avgLowTemp: 6,
      avgRainfallmm: 94,
      avgRainfallDays: 12,
      avgSunshineHours: 220,
      uvIndex: 6,
    },
    {
      cityId: chicago.id,
      month: 5,
      avgHighTemp: 22,
      avgLowTemp: 12,
      avgRainfallmm: 99,
      avgRainfallDays: 12,
      avgSunshineHours: 280,
      uvIndex: 7,
    },
    {
      cityId: chicago.id,
      month: 6,
      avgHighTemp: 27,
      avgLowTemp: 17,
      avgRainfallmm: 104,
      avgRainfallDays: 11,
      avgSunshineHours: 310,
      uvIndex: 8,
    },
    {
      cityId: chicago.id,
      month: 7,
      avgHighTemp: 29,
      avgLowTemp: 20,
      avgRainfallmm: 104,
      avgRainfallDays: 10,
      avgSunshineHours: 320,
      uvIndex: 8,
    },
    {
      cityId: chicago.id,
      month: 8,
      avgHighTemp: 28,
      avgLowTemp: 19,
      avgRainfallmm: 97,
      avgRainfallDays: 10,
      avgSunshineHours: 290,
      uvIndex: 7,
    },
    {
      cityId: chicago.id,
      month: 9,
      avgHighTemp: 24,
      avgLowTemp: 15,
      avgRainfallmm: 84,
      avgRainfallDays: 9,
      avgSunshineHours: 240,
      uvIndex: 5,
    },
    {
      cityId: chicago.id,
      month: 10,
      avgHighTemp: 17,
      avgLowTemp: 8,
      avgRainfallmm: 76,
      avgRainfallDays: 10,
      avgSunshineHours: 180,
      uvIndex: 4,
    },
    {
      cityId: chicago.id,
      month: 11,
      avgHighTemp: 9,
      avgLowTemp: 1,
      avgRainfallmm: 71,
      avgRainfallDays: 10,
      avgSunshineHours: 130,
      uvIndex: 2,
    },
    {
      cityId: chicago.id,
      month: 12,
      avgHighTemp: 2,
      avgLowTemp: -6,
      avgRainfallmm: 64,
      avgRainfallDays: 11,
      avgSunshineHours: 120,
      uvIndex: 2,
    },
  ]);

  // Create Houston
  console.log("Adding city: Houston.");
  const houston = await models.Cities.create({
    city: "Houston",
    country: "United States",
    latitude: 29.7604,
    longitude: -95.3698,
  });

  console.log("Adding climate data: Houston.");
  await models.Climate.bulkCreate([{
      cityId: houston.id,
      month: 1,
      avgHighTemp: 17,
      avgLowTemp: 6,
      avgRainfallmm: 91,
      avgRainfallDays: 10,
      avgSunshineHours: 150,
      uvIndex: 4,
    },
    {
      cityId: houston.id,
      month: 2,
      avgHighTemp: 20,
      avgLowTemp: 9,
      avgRainfallmm: 76,
      avgRainfallDays: 8,
      avgSunshineHours: 180,
      uvIndex: 5,
    },
    {
      cityId: houston.id,
      month: 3,
      avgHighTemp: 24,
      avgLowTemp: 13,
      avgRainfallmm: 84,
      avgRainfallDays: 9,
      avgSunshineHours: 220,
      uvIndex: 7,
    },
    {
      cityId: houston.id,
      month: 4,
      avgHighTemp: 28,
      avgLowTemp: 18,
      avgRainfallmm: 91,
      avgRainfallDays: 7,
      avgSunshineHours: 240,
      uvIndex: 8,
    },
    {
      cityId: houston.id,
      month: 5,
      avgHighTemp: 32,
      avgLowTemp: 23,
      avgRainfallmm: 119,
      avgRainfallDays: 9,
      avgSunshineHours: 280,
      uvIndex: 10,
    },
    {
      cityId: houston.id,
      month: 6,
      avgHighTemp: 35,
      avgLowTemp: 26,
      avgRainfallmm: 158,
      avgRainfallDays: 10,
      avgSunshineHours: 300,
      uvIndex: 11,
    },
    {
      cityId: houston.id,
      month: 7,
      avgHighTemp: 36,
      avgLowTemp: 27,
      avgRainfallmm: 97,
      avgRainfallDays: 8,
      avgSunshineHours: 320,
      uvIndex: 11,
    },
    {
      cityId: houston.id,
      month: 8,
      avgHighTemp: 36,
      avgLowTemp: 27,
      avgRainfallmm: 99,
      avgRainfallDays: 8,
      avgSunshineHours: 310,
      uvIndex: 10,
    },
    {
      cityId: houston.id,
      month: 9,
      avgHighTemp: 33,
      avgLowTemp: 24,
      avgRainfallmm: 104,
      avgRainfallDays: 8,
      avgSunshineHours: 260,
      uvIndex: 8,
    },
    {
      cityId: houston.id,
      month: 10,
      avgHighTemp: 28,
      avgLowTemp: 18,
      avgRainfallmm: 94,
      avgRainfallDays: 7,
      avgSunshineHours: 220,
      uvIndex: 6,
    },
    {
      cityId: houston.id,
      month: 11,
      avgHighTemp: 22,
      avgLowTemp: 11,
      avgRainfallmm: 89,
      avgRainfallDays: 8,
      avgSunshineHours: 180,
      uvIndex: 5,
    },
    {
      cityId: houston.id,
      month: 12,
      avgHighTemp: 18,
      avgLowTemp: 7,
      avgRainfallmm: 89,
      avgRainfallDays: 9,
      avgSunshineHours: 160,
      uvIndex: 4,
    },
  ]);

  console.log("Climate data initialization complete for all cities.");
}
