// data.js

export async function climateData(models) {
  console.log("Adding city: Paris.");
  const paris = await models.Cities.create({
    city: "Paris",
    country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
  });

  console.log("Adding climate data: Paris.");
  await models.Climate.bulkCreate([{
      cityId: paris.id,
      month: 1,
      avgHighTemp: 7,
      avgLowTemp: 3,
      avgRainfallmm: 54,
      avgRainfallDays: 15,
      avgSunshineHours: 62,
    },
    {
      cityId: paris.id,
      month: 2,
      avgHighTemp: 9,
      avgLowTemp: 3,
      avgRainfallmm: 46,
      avgRainfallDays: 13,
      avgSunshineHours: 88,
    },
    {
      cityId: paris.id,
      month: 3,
      avgHighTemp: 12,
      avgLowTemp: 5,
      avgRainfallmm: 51,
      avgRainfallDays: 13,
      avgSunshineHours: 118,
    },
    {
      cityId: paris.id,
      month: 4,
      avgHighTemp: 16,
      avgLowTemp: 8,
      avgRainfallmm: 45,
      avgRainfallDays: 12,
      avgSunshineHours: 178,
    },
    {
      cityId: paris.id,
      month: 5,
      avgHighTemp: 20,
      avgLowTemp: 12,
      avgRainfallmm: 60,
      avgRainfallDays: 12,
      avgSunshineHours: 190,
    },
    {
      cityId: paris.id,
      month: 6,
      avgHighTemp: 23,
      avgLowTemp: 15,
      avgRainfallmm: 54,
      avgRainfallDays: 10,
      avgSunshineHours: 212,
    },
    {
      cityId: paris.id,
      month: 7,
      avgHighTemp: 25,
      avgLowTemp: 17,
      avgRainfallmm: 58,
      avgRainfallDays: 10,
      avgSunshineHours: 212,
    },
    {
      cityId: paris.id,
      month: 8,
      avgHighTemp: 25,
      avgLowTemp: 17,
      avgRainfallmm: 51,
      avgRainfallDays: 9,
      avgSunshineHours: 212,
    },
    {
      cityId: paris.id,
      month: 9,
      avgHighTemp: 21,
      avgLowTemp: 14,
      avgRainfallmm: 54,
      avgRainfallDays: 10,
      avgSunshineHours: 168,
    },
    {
      cityId: paris.id,
      month: 10,
      avgHighTemp: 16,
      avgLowTemp: 10,
      avgRainfallmm: 57,
      avgRainfallDays: 12,
      avgSunshineHours: 124,
    },
    {
      cityId: paris.id,
      month: 11,
      avgHighTemp: 10,
      avgLowTemp: 6,
      avgRainfallmm: 52,
      avgRainfallDays: 15,
      avgSunshineHours: 66,
    },
    {
      cityId: paris.id,
      month: 12,
      avgHighTemp: 7,
      avgLowTemp: 4,
      avgRainfallmm: 55,
      avgRainfallDays: 15,
      avgSunshineHours: 54,
    },
  ]);

  // Create Budapest city
  const budapest = await models.Cities.create({
    city: "Budapest",
    country: "Hungary",
    latitude: 47.4979,
    longitude: 19.0402,
  });

  console.log("Adding climate data: Budapest.");
  await models.Climate.bulkCreate([{
      cityId: budapest.id,
      month: 1,
      avgHighTemp: 3,
      avgLowTemp: -2,
      avgRainfallmm: 35,
      avgRainfallDays: 10,
      avgSunshineHours: 45,
    },
    {
      cityId: budapest.id,
      month: 2,
      avgHighTemp: 6,
      avgLowTemp: -1,
      avgRainfallmm: 30,
      avgRainfallDays: 9,
      avgSunshineHours: 80,
    },
    {
      cityId: budapest.id,
      month: 3,
      avgHighTemp: 12,
      avgLowTemp: 1,
      avgRainfallmm: 40,
      avgRainfallDays: 11,
      avgSunshineHours: 130,
    },
    {
      cityId: budapest.id,
      month: 4,
      avgHighTemp: 17,
      avgLowTemp: 6,
      avgRainfallmm: 50,
      avgRainfallDays: 11,
      avgSunshineHours: 180,
    },
    {
      cityId: budapest.id,
      month: 5,
      avgHighTemp: 22,
      avgLowTemp: 11,
      avgRainfallmm: 60,
      avgRainfallDays: 12,
      avgSunshineHours: 210,
    },
    {
      cityId: budapest.id,
      month: 6,
      avgHighTemp: 26,
      avgLowTemp: 15,
      avgRainfallmm: 70,
      avgRainfallDays: 12,
      avgSunshineHours: 220,
    },
    {
      cityId: budapest.id,
      month: 7,
      avgHighTemp: 28,
      avgLowTemp: 17,
      avgRainfallmm: 55,
      avgRainfallDays: 10,
      avgSunshineHours: 230,
    },
    {
      cityId: budapest.id,
      month: 8,
      avgHighTemp: 28,
      avgLowTemp: 16,
      avgRainfallmm: 65,
      avgRainfallDays: 11,
      avgSunshineHours: 210,
    },
    {
      cityId: budapest.id,
      month: 9,
      avgHighTemp: 24,
      avgLowTemp: 12,
      avgRainfallmm: 50,
      avgRainfallDays: 10,
      avgSunshineHours: 180,
    },
    {
      cityId: budapest.id,
      month: 10,
      avgHighTemp: 17,
      avgLowTemp: 7,
      avgRainfallmm: 40,
      avgRainfallDays: 9,
      avgSunshineHours: 130,
    },
    {
      cityId: budapest.id,
      month: 11,
      avgHighTemp: 10,
      avgLowTemp: 2,
      avgRainfallmm: 35,
      avgRainfallDays: 9,
      avgSunshineHours: 70,
    },
    {
      cityId: budapest.id,
      month: 12,
      avgHighTemp: 5,
      avgLowTemp: -1,
      avgRainfallmm: 30,
      avgRainfallDays: 9,
      avgSunshineHours: 50,
    },
  ]);

  // Create Cape Town city
  const capeTown = await models.Cities.create({
    city: "Cape Town",
    country: "South Africa",
    latitude: -33.9249,
    longitude: 18.4241,
  });

  console.log("Adding climate data: Cape Town.");
  await models.Climate.bulkCreate([{
      cityId: capeTown.id,
      month: 1,
      avgHighTemp: 26,
      avgLowTemp: 16,
      avgRainfallmm: 14,
      avgRainfallDays: 2,
      avgSunshineHours: 350,
    },
    {
      cityId: capeTown.id,
      month: 2,
      avgHighTemp: 27,
      avgLowTemp: 16,
      avgRainfallmm: 18,
      avgRainfallDays: 2,
      avgSunshineHours: 320,
    },
    {
      cityId: capeTown.id,
      month: 3,
      avgHighTemp: 25,
      avgLowTemp: 15,
      avgRainfallmm: 20,
      avgRainfallDays: 3,
      avgSunshineHours: 290,
    },
    {
      cityId: capeTown.id,
      month: 4,
      avgHighTemp: 23,
      avgLowTemp: 13,
      avgRainfallmm: 40,
      avgRainfallDays: 5,
      avgSunshineHours: 250,
    },
    {
      cityId: capeTown.id,
      month: 5,
      avgHighTemp: 20,
      avgLowTemp: 11,
      avgRainfallmm: 70,
      avgRainfallDays: 8,
      avgSunshineHours: 200,
    },
    {
      cityId: capeTown.id,
      month: 6,
      avgHighTemp: 18,
      avgLowTemp: 9,
      avgRainfallmm: 90,
      avgRainfallDays: 10,
      avgSunshineHours: 180,
    },
    {
      cityId: capeTown.id,
      month: 7,
      avgHighTemp: 18,
      avgLowTemp: 8,
      avgRainfallmm: 80,
      avgRainfallDays: 9,
      avgSunshineHours: 190,
    },
    {
      cityId: capeTown.id,
      month: 8,
      avgHighTemp: 19,
      avgLowTemp: 9,
      avgRainfallmm: 77,
      avgRainfallDays: 9,
      avgSunshineHours: 210,
    },
    {
      cityId: capeTown.id,
      month: 9,
      avgHighTemp: 20,
      avgLowTemp: 10,
      avgRainfallmm: 40,
      avgRainfallDays: 6,
      avgSunshineHours: 250,
    },
    {
      cityId: capeTown.id,
      month: 10,
      avgHighTemp: 22,
      avgLowTemp: 12,
      avgRainfallmm: 30,
      avgRainfallDays: 4,
      avgSunshineHours: 280,
    },
    {
      cityId: capeTown.id,
      month: 11,
      avgHighTemp: 24,
      avgLowTemp: 14,
      avgRainfallmm: 18,
      avgRainfallDays: 3,
      avgSunshineHours: 310,
    },
    {
      cityId: capeTown.id,
      month: 12,
      avgHighTemp: 26,
      avgLowTemp: 16,
      avgRainfallmm: 15,
      avgRainfallDays: 2,
      avgSunshineHours: 340,
    },
  ]);

  // Create Berlin city
  const berlin = await models.Cities.create({
    city: "Berlin",
    country: "Germany",
    latitude: 52.52,
    longitude: 13.405,
  });

  console.log("Adding climate data: Berlin.");
  await models.Climate.bulkCreate([{
      cityId: berlin.id,
      month: 1,
      avgHighTemp: 3,
      avgLowTemp: -2,
      avgRainfallmm: 42,
      avgRainfallDays: 10,
      avgSunshineHours: 45,
    },
    {
      cityId: berlin.id,
      month: 2,
      avgHighTemp: 5,
      avgLowTemp: -2,
      avgRainfallmm: 34,
      avgRainfallDays: 8,
      avgSunshineHours: 75,
    },
    {
      cityId: berlin.id,
      month: 3,
      avgHighTemp: 10,
      avgLowTemp: 1,
      avgRainfallmm: 40,
      avgRainfallDays: 9,
      avgSunshineHours: 110,
    },
    {
      cityId: berlin.id,
      month: 4,
      avgHighTemp: 15,
      avgLowTemp: 5,
      avgRainfallmm: 41,
      avgRainfallDays: 8,
      avgSunshineHours: 160,
    },
    {
      cityId: berlin.id,
      month: 5,
      avgHighTemp: 20,
      avgLowTemp: 10,
      avgRainfallmm: 55,
      avgRainfallDays: 9,
      avgSunshineHours: 220,
    },
    {
      cityId: berlin.id,
      month: 6,
      avgHighTemp: 23,
      avgLowTemp: 13,
      avgRainfallmm: 68,
      avgRainfallDays: 10,
      avgSunshineHours: 230,
    },
    {
      cityId: berlin.id,
      month: 7,
      avgHighTemp: 25,
      avgLowTemp: 15,
      avgRainfallmm: 58,
      avgRainfallDays: 9,
      avgSunshineHours: 235,
    },
    {
      cityId: berlin.id,
      month: 8,
      avgHighTemp: 24,
      avgLowTemp: 14,
      avgRainfallmm: 58,
      avgRainfallDays: 8,
      avgSunshineHours: 225,
    },
    {
      cityId: berlin.id,
      month: 9,
      avgHighTemp: 20,
      avgLowTemp: 11,
      avgRainfallmm: 45,
      avgRainfallDays: 8,
      avgSunshineHours: 165,
    },
    {
      cityId: berlin.id,
      month: 10,
      avgHighTemp: 14,
      avgLowTemp: 7,
      avgRainfallmm: 36,
      avgRainfallDays: 9,
      avgSunshineHours: 110,
    },
    {
      cityId: berlin.id,
      month: 11,
      avgHighTemp: 8,
      avgLowTemp: 3,
      avgRainfallmm: 48,
      avgRainfallDays: 10,
      avgSunshineHours: 55,
    },
    {
      cityId: berlin.id,
      month: 12,
      avgHighTemp: 4,
      avgLowTemp: 0,
      avgRainfallmm: 51,
      avgRainfallDays: 11,
      avgSunshineHours: 45,
    },
  ]);

  // Create London city
  const london = await models.Cities.create({
    city: "London",
    country: "United Kingdom",
    latitude: 51.5072,
    longitude: -0.1276,
  });

  console.log("Adding climate data: London.");
  await models.Climate.bulkCreate([{
      cityId: london.id,
      month: 1,
      avgHighTemp: 8,
      avgLowTemp: 3,
      avgRainfallmm: 55,
      avgRainfallDays: 12,
      avgSunshineHours: 61,
    },
    {
      cityId: london.id,
      month: 2,
      avgHighTemp: 8,
      avgLowTemp: 3,
      avgRainfallmm: 40,
      avgRainfallDays: 9,
      avgSunshineHours: 78,
    },
    {
      cityId: london.id,
      month: 3,
      avgHighTemp: 11,
      avgLowTemp: 5,
      avgRainfallmm: 42,
      avgRainfallDays: 9,
      avgSunshineHours: 115,
    },
    {
      cityId: london.id,
      month: 4,
      avgHighTemp: 14,
      avgLowTemp: 7,
      avgRainfallmm: 43,
      avgRainfallDays: 8,
      avgSunshineHours: 168,
    },
    {
      cityId: london.id,
      month: 5,
      avgHighTemp: 18,
      avgLowTemp: 10,
      avgRainfallmm: 47,
      avgRainfallDays: 8,
      avgSunshineHours: 192,
    },
    {
      cityId: london.id,
      month: 6,
      avgHighTemp: 21,
      avgLowTemp: 13,
      avgRainfallmm: 45,
      avgRainfallDays: 7,
      avgSunshineHours: 200,
    },
    {
      cityId: london.id,
      month: 7,
      avgHighTemp: 24,
      avgLowTemp: 15,
      avgRainfallmm: 40,
      avgRainfallDays: 6,
      avgSunshineHours: 212,
    },
    {
      cityId: london.id,
      month: 8,
      avgHighTemp: 23,
      avgLowTemp: 15,
      avgRainfallmm: 48,
      avgRainfallDays: 7,
      avgSunshineHours: 202,
    },
    {
      cityId: london.id,
      month: 9,
      avgHighTemp: 20,
      avgLowTemp: 13,
      avgRainfallmm: 49,
      avgRainfallDays: 8,
      avgSunshineHours: 150,
    },
    {
      cityId: london.id,
      month: 10,
      avgHighTemp: 15,
      avgLowTemp: 10,
      avgRainfallmm: 71,
      avgRainfallDays: 10,
      avgSunshineHours: 116,
    },
    {
      cityId: london.id,
      month: 11,
      avgHighTemp: 11,
      avgLowTemp: 6,
      avgRainfallmm: 63,
      avgRainfallDays: 10,
      avgSunshineHours: 70,
    },
    {
      cityId: london.id,
      month: 12,
      avgHighTemp: 8,
      avgLowTemp: 4,
      avgRainfallmm: 55,
      avgRainfallDays: 11,
      avgSunshineHours: 57,
    },
  ]);

  // Create Nairobi city
  const nairobi = await models.Cities.create({
    city: "Nairobi",
    country: "Kenya",
    latitude: -1.286389,
    longitude: 36.817223,
  });

  console.log("Adding climate data: Nairobi.");
  await models.Climate.bulkCreate([{
      cityId: nairobi.id,
      month: 1,
      avgHighTemp: 26,
      avgLowTemp: 13,
      avgRainfallmm: 50,
      avgRainfallDays: 5,
      avgSunshineHours: 270,
    },
    {
      cityId: nairobi.id,
      month: 2,
      avgHighTemp: 27,
      avgLowTemp: 13,
      avgRainfallmm: 40,
      avgRainfallDays: 4,
      avgSunshineHours: 260,
    },
    {
      cityId: nairobi.id,
      month: 3,
      avgHighTemp: 27,
      avgLowTemp: 14,
      avgRainfallmm: 90,
      avgRainfallDays: 9,
      avgSunshineHours: 240,
    },
    {
      cityId: nairobi.id,
      month: 4,
      avgHighTemp: 25,
      avgLowTemp: 14,
      avgRainfallmm: 240,
      avgRainfallDays: 17,
      avgSunshineHours: 180,
    },
    {
      cityId: nairobi.id,
      month: 5,
      avgHighTemp: 24,
      avgLowTemp: 13,
      avgRainfallmm: 180,
      avgRainfallDays: 15,
      avgSunshineHours: 170,
    },
    {
      cityId: nairobi.id,
      month: 6,
      avgHighTemp: 22,
      avgLowTemp: 11,
      avgRainfallmm: 30,
      avgRainfallDays: 4,
      avgSunshineHours: 200,
    },
    {
      cityId: nairobi.id,
      month: 7,
      avgHighTemp: 21,
      avgLowTemp: 10,
      avgRainfallmm: 20,
      avgRainfallDays: 3,
      avgSunshineHours: 210,
    },
    {
      cityId: nairobi.id,
      month: 8,
      avgHighTemp: 22,
      avgLowTemp: 10,
      avgRainfallmm: 20,
      avgRainfallDays: 3,
      avgSunshineHours: 210,
    },
    {
      cityId: nairobi.id,
      month: 9,
      avgHighTemp: 25,
      avgLowTemp: 12,
      avgRainfallmm: 30,
      avgRainfallDays: 4,
      avgSunshineHours: 230,
    },
    {
      cityId: nairobi.id,
      month: 10,
      avgHighTemp: 26,
      avgLowTemp: 13,
      avgRainfallmm: 90,
      avgRainfallDays: 9,
      avgSunshineHours: 220,
    },
    {
      cityId: nairobi.id,
      month: 11,
      avgHighTemp: 24,
      avgLowTemp: 13,
      avgRainfallmm: 150,
      avgRainfallDays: 13,
      avgSunshineHours: 200,
    },
    {
      cityId: nairobi.id,
      month: 12,
      avgHighTemp: 24,
      avgLowTemp: 13,
      avgRainfallmm: 70,
      avgRainfallDays: 6,
      avgSunshineHours: 240,
    },
  ]);

  // Create Tokyo city
  const tokyo = await models.Cities.create({
    city: "Tokyo",
    country: "Japan",
    latitude: 35.6895,
    longitude: 139.6917,
  });

  console.log("Adding climate data: Tokyo.");
  await models.Climate.bulkCreate([{
      cityId: tokyo.id,
      month: 1,
      avgHighTemp: 10,
      avgLowTemp: 2,
      avgRainfallmm: 50,
      avgRainfallDays: 5,
      avgSunshineHours: 180,
    },
    {
      cityId: tokyo.id,
      month: 2,
      avgHighTemp: 11,
      avgLowTemp: 2,
      avgRainfallmm: 60,
      avgRainfallDays: 6,
      avgSunshineHours: 175,
    },
    {
      cityId: tokyo.id,
      month: 3,
      avgHighTemp: 14,
      avgLowTemp: 5,
      avgRainfallmm: 110,
      avgRainfallDays: 10,
      avgSunshineHours: 160,
    },
    {
      cityId: tokyo.id,
      month: 4,
      avgHighTemp: 19,
      avgLowTemp: 10,
      avgRainfallmm: 125,
      avgRainfallDays: 10,
      avgSunshineHours: 170,
    },
    {
      cityId: tokyo.id,
      month: 5,
      avgHighTemp: 23,
      avgLowTemp: 15,
      avgRainfallmm: 135,
      avgRainfallDays: 10,
      avgSunshineHours: 170,
    },
    {
      cityId: tokyo.id,
      month: 6,
      avgHighTemp: 25,
      avgLowTemp: 19,
      avgRainfallmm: 160,
      avgRainfallDays: 12,
      avgSunshineHours: 130,
    },
    {
      cityId: tokyo.id,
      month: 7,
      avgHighTemp: 29,
      avgLowTemp: 23,
      avgRainfallmm: 155,
      avgRainfallDays: 10,
      avgSunshineHours: 170,
    },
    {
      cityId: tokyo.id,
      month: 8,
      avgHighTemp: 31,
      avgLowTemp: 24,
      avgRainfallmm: 170,
      avgRainfallDays: 10,
      avgSunshineHours: 190,
    },
    {
      cityId: tokyo.id,
      month: 9,
      avgHighTemp: 27,
      avgLowTemp: 21,
      avgRainfallmm: 210,
      avgRainfallDays: 12,
      avgSunshineHours: 140,
    },
    {
      cityId: tokyo.id,
      month: 10,
      avgHighTemp: 21,
      avgLowTemp: 15,
      avgRainfallmm: 160,
      avgRainfallDays: 9,
      avgSunshineHours: 165,
    },
    {
      cityId: tokyo.id,
      month: 11,
      avgHighTemp: 16,
      avgLowTemp: 9,
      avgRainfallmm: 90,
      avgRainfallDays: 6,
      avgSunshineHours: 170,
    },
    {
      cityId: tokyo.id,
      month: 12,
      avgHighTemp: 12,
      avgLowTemp: 5,
      avgRainfallmm: 50,
      avgRainfallDays: 4,
      avgSunshineHours: 180,
    },
  ]);




}
