services:
  grackle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grackle
    restart: unless-stopped
    env_file: .env
    ports:
      - "5555:8080"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - .data:/usr/src/app/.data

volumes:
  .data:
  node_modules:
